// File autogenerated by hexa.run on 2020-02-11T17:28:27.872Z
import { AzureFunction, Context, HttpRequest } from "@azure/functions";
import { generate } from "./wasm_loader";


const wasm_gen: AzureFunction = async function (context: Context, req: HttpRequest): Promise<void> {
    context.res = {
        body: {
            project: await generate()
        }
    };
};

export default wasm_gen;
